version: "3.8"

services:
  postgres:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
    - $PWD/src/main/resources/val/:/docker-entrypoint-initdb.d/

#  java-app:
#    depends_on:
#      - "postgres"
#    container_name: java-app
##    image: cmmttd/dev-interview-bot
##    image: financial-helper
#    image: fiolent/finhelper
#    ports:
#      - 8080:8080
##    volumes:
##      - $PWD/build/libs/*.jar:/usr/app/app.jar

